// src/components/MiosaActivityFeed.tsx
import React, { useCallback, useEffect, useRef, useState } from "react";
import { cn } from "../utils/cn.js";
import { getClient } from "../utils/client.js";
import type { MiosaBaseProps } from "../types.js";

export interface MiosaActivityFeedProps extends MiosaBaseProps {
  scope?: string;
  apiKey: string;
  unstyled?: boolean;
  style?: React.CSSProperties;
}

interface FeedEvent {
  id: string;
  ts: string;
  type: string;
  actor?: string;
  resource?: string;
  data?: Record<string, unknown>;
}

const EVENT_CATEGORIES = [
  "sandbox",
  "member",
  "policy",
  "quota",
  "workspace",
] as const;
type EventCategory = (typeof EVENT_CATEGORIES)[number];

function categoryOf(type: string): EventCategory | "other" {
  for (const cat of EVENT_CATEGORIES) {
    if (type.startsWith(cat + ".")) return cat;
  }
  return "other";
}

export function MiosaActivityFeed({
  scope,
  apiKey,
  theme = "dark",
  onError,
  className,
  style,
  unstyled = false,
}: MiosaActivityFeedProps): React.ReactElement {
  const [events, setEvents] = useState<FeedEvent[]>([]);
  const [connected, setConnected] = useState(false);
  const [activeCategories, setActiveCategories] = useState<
    Set<EventCategory | "other">
  >(new Set());
  const esRef = useRef<EventSource | null>(null);
  const newIdsRef = useRef<Set<string>>(new Set());

  const toggleCategory = useCallback((cat: EventCategory | "other") => {
    setActiveCategories((prev) => {
      const next = new Set(prev);
      if (next.has(cat)) next.delete(cat);
      else next.add(cat);
      return next;
    });
  }, []);

  useEffect(() => {
    const client = getClient(apiKey);
    const c = client as unknown as {
      tenant?: {
        events?: {
          stream: (params: { types: string[]; scope?: string }) => EventSource;
        };
      };
    };

    if (!c.tenant?.events?.stream) return;

    const es = c.tenant.events.stream({
      types: ["*"],
      scope: scope ?? "all",
    });

    esRef.current = es;

    es.onopen = () => setConnected(true);
    es.onerror = () => {
      setConnected(false);
      onError?.(new Error("Activity feed disconnected"));
    };

    es.onmessage = (msg: MessageEvent<string>) => {
      try {
        const ev = JSON.parse(msg.data) as FeedEvent;
        newIdsRef.current.add(ev.id);
        setEvents((prev) => [ev, ...prev].slice(0, 200));
        // Fade-in: remove the "new" marker after animation completes
        setTimeout(() => {
          newIdsRef.current.delete(ev.id);
        }, 600);
      } catch {
        // ignore parse errors
      }
    };

    return () => {
      es.close();
      setConnected(false);
    };
  }, [apiKey, scope, onError]);

  const base = "miosa-af";

  const filtered =
    activeCategories.size === 0
      ? events
      : events.filter((ev) => activeCategories.has(categoryOf(ev.type)));

  return (
    <div
      className={cn(
        !unstyled && base,
        !unstyled && `${base}--${theme}`,
        className,
      )}
      style={style}
      data-miosa-theme={theme}
    >
      <div className={`${base}__header`}>
        <span
          className={cn(
            `${base}__status`,
            connected ? `${base}__status--live` : `${base}__status--offline`,
          )}
          aria-label={connected ? "Live" : "Disconnected"}
        >
          {connected ? "● Live" : "○ Disconnected"}
        </span>
        <div
          className={`${base}__chips`}
          role="group"
          aria-label="Filter by category"
        >
          {EVENT_CATEGORIES.map((cat) => (
            <button
              key={cat}
              type="button"
              className={cn(
                `${base}__chip`,
                activeCategories.has(cat) && `${base}__chip--active`,
              )}
              onClick={() => toggleCategory(cat)}
              aria-pressed={activeCategories.has(cat)}
            >
              {cat}
            </button>
          ))}
        </div>
      </div>

      <ul
        className={`${base}__list`}
        role="list"
        aria-label="Activity feed"
        aria-live="polite"
        aria-atomic="false"
        aria-relevant="additions"
      >
        {filtered.map((ev) => (
          <li
            key={ev.id}
            className={cn(
              `${base}__item`,
              newIdsRef.current.has(ev.id) && `${base}__item--new`,
            )}
          >
            <span className={`${base}__event-type`}>{ev.type}</span>
            {ev.actor && (
              <span className={`${base}__event-actor`}>{ev.actor}</span>
            )}
            {ev.resource && (
              <span className={`${base}__event-resource`}>{ev.resource}</span>
            )}
            <span className={`${base}__event-ts`}>
              {new Date(ev.ts).toLocaleTimeString()}
            </span>
          </li>
        ))}
        {filtered.length === 0 && (
          <li className={`${base}__empty`}>
            {connected ? "Waiting for events…" : "Not connected"}
          </li>
        )}
      </ul>
    </div>
  );
}

// vue/src/components/MiosaActivityFeed.vue
<script setup lang="ts">
import { Miosa } from "@miosa/sdk";
import { onMounted, onUnmounted, ref } from "vue";

interface FeedEvent {
  id: string;
  ts: string;
  type: string;
  actor?: string;
  resource?: string;
}

const EVENT_CATEGORIES = ["sandbox", "member", "policy", "quota", "workspace"] as const;
type EventCategory = (typeof EVENT_CATEGORIES)[number];

const props = withDefaults(
  defineProps<{
    scope?: string;
    apiKey: string;
    theme?: "light" | "dark";
    unstyled?: boolean;
    onError?: (err: Error) => void;
  }>(),
  { theme: "dark", unstyled: false },
);

const events = ref<FeedEvent[]>([]);
const connected = ref(false);
const activeCategories = ref<Set<EventCategory | "other">>(new Set());
const newIds = ref<Set<string>>(new Set());
let es: EventSource | null = null;

function categoryOf(type: string): EventCategory | "other" {
  for (const cat of EVENT_CATEGORIES) {
    if (type.startsWith(cat + ".")) return cat;
  }
  return "other";
}

function toggleCategory(cat: EventCategory | "other") {
  const s = new Set(activeCategories.value);
  if (s.has(cat)) s.delete(cat);
  else s.add(cat);
  activeCategories.value = s;
}

function filteredEvents() {
  if (activeCategories.value.size === 0) return events.value;
  return events.value.filter((ev) => activeCategories.value.has(categoryOf(ev.type)));
}

onMounted(() => {
  interface StreamSdk {
    tenant: { events: { stream: (p: { types: string[]; scope?: string }) => EventSource } };
  }
  const c = new Miosa({ apiKey: props.apiKey }) as unknown as StreamSdk;
  if (!c.tenant?.events?.stream) return;

  es = c.tenant.events.stream({ types: ["*"], scope: props.scope ?? "all" });
  es.onopen = () => { connected.value = true; };
  es.onerror = () => {
    connected.value = false;
    props.onError?.(new Error("Activity feed disconnected"));
  };
  es.onmessage = (msg: MessageEvent<string>) => {
    try {
      const ev = JSON.parse(msg.data) as FeedEvent;
      newIds.value = new Set([...newIds.value, ev.id]);
      events.value = [ev, ...events.value].slice(0, 200);
      setTimeout(() => {
        const s = new Set(newIds.value);
        s.delete(ev.id);
        newIds.value = s;
      }, 600);
    } catch { /* ignore */ }
  };
});

onUnmounted(() => {
  es?.close();
  connected.value = false;
});
</script>

<template>
  <div
    :class="[!unstyled && 'miosa-af', !unstyled && `miosa-af--${theme}`]"
    :data-miosa-theme="theme"
  >
    <div class="miosa-af__header">
      <span
        :class="['miosa-af__status', connected ? 'miosa-af__status--live' : 'miosa-af__status--offline']"
        :aria-label="connected ? 'Live' : 'Disconnected'"
      >
        {{ connected ? "● Live" : "○ Disconnected" }}
      </span>
      <div class="miosa-af__chips" role="group" aria-label="Filter by category">
        <button
          v-for="cat in EVENT_CATEGORIES"
          :key="cat"
          type="button"
          :class="['miosa-af__chip', activeCategories.has(cat) && 'miosa-af__chip--active']"
          :aria-pressed="activeCategories.has(cat)"
          @click="toggleCategory(cat)"
        >
          {{ cat }}
        </button>
      </div>
    </div>

    <ul
      class="miosa-af__list"
      role="list"
      aria-label="Activity feed"
      aria-live="polite"
      aria-atomic="false"
      aria-relevant="additions"
    >
      <li
        v-for="ev in filteredEvents()"
        :key="ev.id"
        :class="['miosa-af__item', newIds.has(ev.id) && 'miosa-af__item--new']"
      >
        <span class="miosa-af__event-type">{{ ev.type }}</span>
        <span v-if="ev.actor" class="miosa-af__event-actor">{{ ev.actor }}</span>
        <span v-if="ev.resource" class="miosa-af__event-resource">{{ ev.resource }}</span>
        <span class="miosa-af__event-ts">{{ new Date(ev.ts).toLocaleTimeString() }}</span>
      </li>
      <li v-if="filteredEvents().length === 0" class="miosa-af__empty">
        {{ connected ? "Waiting for events…" : "Not connected" }}
      </li>
    </ul>
  </div>
</template>
