// src/components/MiosaBulkActions.tsx
import React, { useCallback, useEffect, useRef, useState } from "react";
import { cn } from "../utils/cn.js";
import { getClient } from "../utils/client.js";
import type { MiosaBaseProps } from "../types.js";

export type BulkAction = "pause" | "resume" | "destroy" | "applyPolicy";

export interface MiosaBulkActionsProps extends MiosaBaseProps {
  selectedIds: string[];
  actions?: BulkAction[];
  apiKey: string;
  unstyled?: boolean;
  style?: React.CSSProperties;
  onComplete?: (action: BulkAction, jobId: string) => void;
}

interface JobStatus {
  id: string;
  action: BulkAction;
  queued: number;
  completed: number;
  failed: number;
  status: "running" | "done" | "error";
}

const ACTION_LABELS: Record<BulkAction, string> = {
  pause: "Pause",
  resume: "Resume",
  destroy: "Destroy",
  applyPolicy: "Apply policy",
};

export function MiosaBulkActions({
  selectedIds,
  actions = ["pause", "resume", "destroy"],
  apiKey,
  theme = "dark",
  onError,
  onComplete,
  className,
  style,
  unstyled = false,
}: MiosaBulkActionsProps): React.ReactElement | null {
  const [pendingAction, setPendingAction] = useState<BulkAction | null>(null);
  const [jobs, setJobs] = useState<JobStatus[]>([]);
  const pollRefs = useRef<Map<string, ReturnType<typeof setInterval>>>(
    new Map(),
  );

  // Clean up polls on unmount
  useEffect(() => {
    const refs = pollRefs.current;
    return () => {
      refs.forEach((timer) => clearInterval(timer));
    };
  }, []);

  const pollJob = useCallback(
    (jobId: string, action: BulkAction) => {
      const timer = setInterval(async () => {
        try {
          const client = getClient(apiKey);
          const raw = await (
            client as unknown as {
              bulk: {
                jobs: { get: (p: { id: string }) => Promise<unknown> };
              };
            }
          ).bulk.jobs.get({ id: jobId });
          const status = raw as {
            status: string;
            completed: number;
            failed: number;
            queued: number;
          };
          const done = status.status === "done" || status.status === "error";

          setJobs((prev) =>
            prev.map((j) =>
              j.id === jobId
                ? {
                    ...j,
                    status: (status.status as JobStatus["status"]) ?? j.status,
                    completed: status.completed ?? j.completed,
                    failed: status.failed ?? j.failed,
                  }
                : j,
            ),
          );

          if (done) {
            clearInterval(timer);
            pollRefs.current.delete(jobId);
            onComplete?.(action, jobId);
          }
        } catch {
          // ignore transient poll errors
        }
      }, 1500);
      pollRefs.current.set(jobId, timer);
    },
    [apiKey, onComplete],
  );

  const handleAction = useCallback(
    async (action: BulkAction) => {
      if (selectedIds.length === 0) return;
      const label = ACTION_LABELS[action];
      const destructive = action === "destroy";
      if (
        destructive &&
        !window.confirm(
          `${label} ${selectedIds.length} sandbox(es)? This cannot be undone.`,
        )
      )
        return;
      if (
        !destructive &&
        !window.confirm(`${label} ${selectedIds.length} sandbox(es)?`)
      )
        return;

      setPendingAction(action);
      try {
        const client = getClient(apiKey);
        const apiAction = action === "applyPolicy" ? "apply_policy" : action;
        const raw = await (
          client as unknown as {
            bulk: {
              sandboxes: Record<
                string,
                (p: { ids: string[] }) => Promise<unknown>
              >;
            };
          }
        ).bulk.sandboxes[apiAction]?.({ ids: selectedIds });

        const res = raw as { job_id?: string; queued?: number };
        if (res.job_id) {
          const newJob: JobStatus = {
            id: res.job_id,
            action,
            queued: res.queued ?? selectedIds.length,
            completed: 0,
            failed: 0,
            status: "running",
          };
          setJobs((prev) => [newJob, ...prev]);
          pollJob(res.job_id, action);
        }
      } catch (err) {
        const error = err instanceof Error ? err : new Error(String(err));
        onError?.(error);
      } finally {
        setPendingAction(null);
      }
    },
    [selectedIds, apiKey, pollJob, onError],
  );

  if (selectedIds.length === 0 && jobs.length === 0) return null;

  const base = "miosa-ba";

  return (
    <div
      className={cn(
        !unstyled && base,
        !unstyled && `${base}--${theme}`,
        !unstyled && `${base}--sticky`,
        className,
      )}
      style={style}
      data-miosa-theme={theme}
      role="toolbar"
      aria-label="Bulk actions"
    >
      {selectedIds.length > 0 && (
        <div className={`${base}__bar`}>
          <span className={`${base}__count`}>
            {selectedIds.length} selected
          </span>
          <div className={`${base}__actions`}>
            {actions.map((action) => (
              <button
                key={action}
                type="button"
                className={cn(
                  `${base}__action-btn`,
                  action === "destroy" && `${base}__action-btn--danger`,
                )}
                onClick={() => void handleAction(action)}
                disabled={pendingAction !== null}
                aria-label={`${ACTION_LABELS[action]} ${selectedIds.length} items`}
              >
                {pendingAction === action
                  ? "…"
                  : `${ACTION_LABELS[action]} (${selectedIds.length})`}
              </button>
            ))}
          </div>
        </div>
      )}

      {jobs.length > 0 && (
        <div className={`${base}__jobs`} aria-label="Job progress">
          {jobs.map((job) => (
            <div key={job.id} className={`${base}__job`}>
              <span className={`${base}__job-label`}>
                {ACTION_LABELS[job.action]}
              </span>
              <progress
                className={`${base}__job-progress`}
                value={job.completed + job.failed}
                max={job.queued}
                aria-label={`${job.completed}/${job.queued} done`}
              />
              <span className={`${base}__job-status`}>
                {job.status === "running"
                  ? `${job.completed}/${job.queued}`
                  : job.status}
              </span>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

// vue/src/components/MiosaBulkActions.vue
<script setup lang="ts">
import { Miosa } from "@miosa/sdk";
import { onUnmounted, ref, computed } from "vue";

type BulkAction = "pause" | "resume" | "destroy" | "applyPolicy";

interface JobStatus {
  id: string;
  action: BulkAction;
  queued: number;
  completed: number;
  failed: number;
  status: "running" | "done" | "error";
}

const ACTION_LABELS: Record<BulkAction, string> = {
  pause: "Pause", resume: "Resume", destroy: "Destroy", applyPolicy: "Apply policy",
};

const props = withDefaults(
  defineProps<{
    selectedIds: string[];
    actions?: BulkAction[];
    apiKey: string;
    theme?: "light" | "dark";
    unstyled?: boolean;
    onError?: (err: Error) => void;
    onComplete?: (action: BulkAction, jobId: string) => void;
  }>(),
  { theme: "dark", unstyled: false, actions: () => ["pause", "resume", "destroy"] as BulkAction[] },
);

const jobs = ref<JobStatus[]>([]);
const pendingAction = ref<BulkAction | null>(null);
const pollTimers = new Map<string, ReturnType<typeof setInterval>>();

const visible = computed(() => props.selectedIds.length > 0 || jobs.value.length > 0);

interface BulkSdk {
  bulk: {
    sandboxes: Record<string, (p: { ids: string[] }) => Promise<unknown>>;
    jobs: { get: (p: { id: string }) => Promise<unknown> };
  };
}

function asApi(apiKey: string): BulkSdk {
  return new Miosa({ apiKey }) as unknown as BulkSdk;
}

function pollJob(jobId: string, action: BulkAction) {
  const timer = setInterval(async () => {
    try {
      const raw = await asApi(props.apiKey).bulk.jobs.get({ id: jobId });
      const s = raw as { status: string; completed: number; failed: number; queued: number };
      const done = s.status === "done" || s.status === "error";
      jobs.value = jobs.value.map((j) =>
        j.id === jobId
          ? { ...j, status: s.status as JobStatus["status"], completed: s.completed ?? j.completed, failed: s.failed ?? j.failed }
          : j,
      );
      if (done) {
        clearInterval(timer);
        pollTimers.delete(jobId);
        props.onComplete?.(action, jobId);
      }
    } catch { /* ignore */ }
  }, 1500);
  pollTimers.set(jobId, timer);
}

async function handleAction(action: BulkAction) {
  if (props.selectedIds.length === 0) return;
  const label = ACTION_LABELS[action];
  if (action === "destroy" && !window.confirm(`${label} ${props.selectedIds.length} sandbox(es)? This cannot be undone.`)) return;
  if (action !== "destroy" && !window.confirm(`${label} ${props.selectedIds.length} sandbox(es)?`)) return;
  pendingAction.value = action;
  try {
    const apiAction = action === "applyPolicy" ? "apply_policy" : action;
    const raw = await asApi(props.apiKey).bulk.sandboxes[apiAction]?.({ ids: props.selectedIds });
    const res = raw as { job_id?: string; queued?: number };
    if (res.job_id) {
      jobs.value = [
        { id: res.job_id, action, queued: res.queued ?? props.selectedIds.length, completed: 0, failed: 0, status: "running" },
        ...jobs.value,
      ];
      pollJob(res.job_id, action);
    }
  } catch (e) {
    props.onError?.(e instanceof Error ? e : new Error(String(e)));
  } finally {
    pendingAction.value = null;
  }
}

onUnmounted(() => {
  pollTimers.forEach((t) => clearInterval(t));
});
</script>

<template>
  <div
    v-if="visible"
    :class="[!unstyled && 'miosa-ba', !unstyled && `miosa-ba--${theme}`, !unstyled && 'miosa-ba--sticky']"
    :data-miosa-theme="theme"
    role="toolbar"
    aria-label="Bulk actions"
  >
    <div v-if="selectedIds.length > 0" class="miosa-ba__bar">
      <span class="miosa-ba__count">{{ selectedIds.length }} selected</span>
      <div class="miosa-ba__actions">
        <button
          v-for="action in actions"
          :key="action"
          type="button"
          :class="['miosa-ba__action-btn', action === 'destroy' && 'miosa-ba__action-btn--danger']"
          :disabled="pendingAction !== null"
          :aria-label="`${ACTION_LABELS[action]} ${selectedIds.length} items`"
          @click="handleAction(action)"
        >
          {{ pendingAction === action ? "…" : `${ACTION_LABELS[action]} (${selectedIds.length})` }}
        </button>
      </div>
    </div>
    <div v-if="jobs.length > 0" class="miosa-ba__jobs" aria-label="Job progress">
      <div v-for="job in jobs" :key="job.id" class="miosa-ba__job">
        <span class="miosa-ba__job-label">{{ ACTION_LABELS[job.action] }}</span>
        <progress class="miosa-ba__job-progress" :value="job.completed + job.failed" :max="job.queued" :aria-label="`${job.completed}/${job.queued} done`" />
        <span class="miosa-ba__job-status">{{ job.status === "running" ? `${job.completed}/${job.queued}` : job.status }}</span>
      </div>
    </div>
  </div>
</template>
