// react/src/components/MiosaBrandingEditor.tsx
import React, { useCallback, useEffect, useState } from "react";
import { cn } from "../utils/cn.js";
import { getClient } from "../utils/client.js";
import type { MiosaBaseProps } from "../types.js";

export interface MiosaBrandingEditorProps extends MiosaBaseProps {
  apiKey: string;
  unstyled?: boolean;
  style?: React.CSSProperties;
  onSave?: (branding: BrandingData) => void;
}

interface BrandingData {
  product_name?: string;
  logo_url?: string;
  support_url?: string;
  primary_color?: string;
  background_color?: string;
}

type State =
  | { status: "loading" }
  | { status: "ready"; branding: BrandingData }
  | { status: "error"; error: Error };

export function MiosaBrandingEditor({
  apiKey,
  theme = "dark",
  onError,
  onSave,
  className,
  style,
  unstyled = false,
}: MiosaBrandingEditorProps): React.ReactElement {
  const [state, setState] = useState<State>({ status: "loading" });
  const [draft, setDraft] = useState<BrandingData>({});
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    let cancelled = false;
    async function load(): Promise<void> {
      try {
        const client = getClient(apiKey);
        const raw = await (
          client as unknown as {
            tenant: { getBranding: () => Promise<unknown> };
          }
        ).tenant.getBranding();
        const data =
          (raw as { data?: BrandingData }).data ?? (raw as BrandingData);
        if (!cancelled) {
          setState({ status: "ready", branding: data });
          setDraft(data);
        }
      } catch (err) {
        const error = err instanceof Error ? err : new Error(String(err));
        if (!cancelled) {
          setState({ status: "error", error });
          onError?.(error);
        }
      }
    }
    void load();
    return () => {
      cancelled = true;
    };
  }, [apiKey, onError]);

  const set = useCallback(
    (key: keyof BrandingData, value: string) =>
      setDraft((d) => ({ ...d, [key]: value || undefined })),
    [],
  );

  const handleSave = useCallback(
    async (e: React.FormEvent) => {
      e.preventDefault();
      if (saving) return;
      setSaving(true);
      try {
        const client = getClient(apiKey);
        await (
          client as unknown as {
            tenant: { setBranding: (p: BrandingData) => Promise<unknown> };
          }
        ).tenant.setBranding(draft);
        onSave?.(draft);
      } catch (err) {
        const error = err instanceof Error ? err : new Error(String(err));
        onError?.(error);
      } finally {
        setSaving(false);
      }
    },
    [apiKey, draft, onSave, onError, saving],
  );

  const base = "miosa-be";

  if (state.status === "loading") {
    return (
      <div
        className={cn(!unstyled && base, className)}
        style={style}
        aria-busy="true"
        aria-label="Loading branding"
      >
        <div className={`${base}__skeleton`} />
      </div>
    );
  }

  if (state.status === "error") {
    return (
      <div
        className={cn(!unstyled && base, className)}
        style={style}
        role="alert"
      >
        {state.error.message}
      </div>
    );
  }

  const previewStyle: React.CSSProperties = {
    background: draft.background_color ?? "#0d0d0d",
    padding: "24px",
    borderRadius: "8px",
    fontFamily: "system-ui, sans-serif",
    color: draft.primary_color ?? "#f0f0f0",
    minHeight: "120px",
  };

  return (
    <div
      className={cn(
        !unstyled && base,
        !unstyled && `${base}--${theme}`,
        className,
      )}
      style={style}
      data-miosa-theme={theme}
    >
      <div className={`${base}__layout`}>
        <form
          className={`${base}__form`}
          onSubmit={handleSave}
          aria-label="Branding settings"
        >
          {(
            [
              ["product_name", "Product name", "text"],
              ["logo_url", "Logo URL", "url"],
              ["support_url", "Support URL", "url"],
              ["primary_color", "Primary color", "color"],
              ["background_color", "Background color", "color"],
            ] as [keyof BrandingData, string, string][]
          ).map(([key, label, inputType]) => (
            <div key={key} className={`${base}__field`}>
              <label className={`${base}__label`} htmlFor={`miosa-be-${key}`}>
                {label}
              </label>
              <input
                id={`miosa-be-${key}`}
                type={inputType}
                className={`${base}__input`}
                value={draft[key] ?? ""}
                onChange={(e) => set(key, e.target.value)}
                aria-label={label}
              />
            </div>
          ))}
          <button
            type="submit"
            className={`${base}__save-btn`}
            disabled={saving}
            aria-label="Save branding"
          >
            {saving ? "Saving…" : "Save branding"}
          </button>
        </form>

        {/* Live preview */}
        <div className={`${base}__preview`} aria-label="Branding preview">
          <h3 className={`${base}__preview-title`}>Preview</h3>
          <div style={previewStyle} role="img" aria-label="Error page preview">
            {draft.logo_url && (
              <img
                src={draft.logo_url}
                alt="Logo"
                style={{ maxHeight: 40, marginBottom: 12 }}
              />
            )}
            <div style={{ fontSize: 18, fontWeight: 600, marginBottom: 8 }}>
              {draft.product_name ?? "Your Product"}
            </div>
            <div style={{ fontSize: 13, opacity: 0.7 }}>
              Something went wrong. Contact{" "}
              {draft.support_url ? (
                <a
                  href={draft.support_url}
                  style={{ color: draft.primary_color }}
                >
                  support
                </a>
              ) : (
                "support"
              )}
              .
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// vue/src/components/MiosaBrandingEditor.vue
<script setup lang="ts">
import { Miosa } from "@miosa/sdk";
import { onMounted, ref, watch } from "vue";

interface BrandingData {
  product_name?: string;
  logo_url?: string;
  support_url?: string;
  primary_color?: string;
  background_color?: string;
}

interface BrandingSdk {
  tenant: {
    getBranding: () => Promise<unknown>;
    setBranding: (p: BrandingData) => Promise<unknown>;
  };
}

const props = withDefaults(
  defineProps<{
    apiKey: string;
    theme?: "light" | "dark";
    unstyled?: boolean;
    onError?: (err: Error) => void;
    onSave?: (branding: BrandingData) => void;
  }>(),
  { theme: "dark", unstyled: false },
);

const draft = ref<BrandingData>({});
const loading = ref(true);
const saving = ref(false);
const error = ref<Error | null>(null);

function asApi(apiKey: string): BrandingSdk {
  return new Miosa({ apiKey }) as unknown as BrandingSdk;
}

async function load() {
  loading.value = true;
  error.value = null;
  try {
    const raw = await asApi(props.apiKey).tenant.getBranding();
    draft.value = ((raw as { data?: BrandingData }).data ?? raw) as BrandingData;
  } catch (e) {
    error.value = e instanceof Error ? e : new Error(String(e));
    props.onError?.(error.value);
  } finally {
    loading.value = false;
  }
}

async function save(e: Event) {
  e.preventDefault();
  if (saving.value) return;
  saving.value = true;
  try {
    await asApi(props.apiKey).tenant.setBranding(draft.value);
    props.onSave?.(draft.value);
  } catch (err) {
    props.onError?.(err instanceof Error ? err : new Error(String(err)));
  } finally {
    saving.value = false;
  }
}

const FIELDS = [
  ["product_name", "Product name", "text"],
  ["logo_url", "Logo URL", "url"],
  ["support_url", "Support URL", "url"],
  ["primary_color", "Primary color", "color"],
  ["background_color", "Background color", "color"],
] as [keyof BrandingData, string, string][];

onMounted(load);
watch(() => props.apiKey, load);
</script>

<template>
  <div
    :class="[!unstyled && 'miosa-be', !unstyled && `miosa-be--${theme}`]"
    :data-miosa-theme="theme"
  >
    <div v-if="loading" class="miosa-be__skeleton" aria-busy="true" aria-label="Loading branding" />
    <div v-else-if="error" role="alert">{{ error.message }}</div>
    <div v-else class="miosa-be__layout">
      <form class="miosa-be__form" aria-label="Branding settings" @submit="save">
        <div v-for="[key, label, inputType] in FIELDS" :key="key" class="miosa-be__field">
          <label :for="`miosa-be-${key}`" class="miosa-be__label">{{ label }}</label>
          <input
            :id="`miosa-be-${key}`"
            :type="inputType"
            class="miosa-be__input"
            :value="draft[key] ?? ''"
            :aria-label="label"
            @input="(e) => { draft[key] = (e.target as HTMLInputElement).value || undefined }"
          />
        </div>
        <button type="submit" class="miosa-be__save-btn" :disabled="saving" aria-label="Save branding">
          {{ saving ? "Saving…" : "Save branding" }}
        </button>
      </form>
      <div class="miosa-be__preview" aria-label="Branding preview">
        <h3 class="miosa-be__preview-title">Preview</h3>
        <div
          role="img"
          aria-label="Error page preview"
          :style="{
            background: draft.background_color ?? '#0d0d0d',
            padding: '24px',
            borderRadius: '8px',
            fontFamily: 'system-ui, sans-serif',
            color: draft.primary_color ?? '#f0f0f0',
            minHeight: '120px',
          }"
        >
          <img v-if="draft.logo_url" :src="draft.logo_url" alt="Logo" style="max-height:40px;margin-bottom:12px" />
          <div style="font-size:18px;font-weight:600;margin-bottom:8px">
            {{ draft.product_name ?? "Your Product" }}
          </div>
          <div style="font-size:13px;opacity:0.7">
            Something went wrong. Contact
            <a v-if="draft.support_url" :href="draft.support_url" :style="{ color: draft.primary_color }">support</a>
            <span v-else>support</span>.
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
