// react/src/components/MiosaApiKeyManager.tsx
import React, { useCallback, useEffect, useState } from "react";
import { cn } from "../utils/cn.js";
import { getClient } from "../utils/client.js";
import type { MiosaBaseProps } from "../types.js";

export interface MiosaApiKeyManagerProps extends MiosaBaseProps {
  apiKey: string;
  unstyled?: boolean;
  style?: React.CSSProperties;
}

const ALL_SCOPES = [
  "sandboxes:read",
  "sandboxes:write",
  "computers:read",
  "computers:write",
  "storage:read",
  "storage:write",
  "databases:read",
  "databases:write",
  "usage:read",
  "audit_log:read",
  "tenant:admin",
];

interface ApiKey {
  id: string;
  name: string;
  last4: string;
  scopes: string[];
  created_at: string;
  last_used_at?: string;
  expires_at?: string;
  external_user_id?: string;
}

type State =
  | { status: "loading" }
  | { status: "ready"; keys: ApiKey[] }
  | { status: "error"; error: Error };

interface CreateForm {
  name: string;
  scopes: string[];
  expires_at: string;
  external_user_id: string;
  isL2: boolean;
}

const DEFAULT_FORM: CreateForm = {
  name: "",
  scopes: [],
  expires_at: "",
  external_user_id: "",
  isL2: false,
};

export function MiosaApiKeyManager({
  apiKey,
  theme = "dark",
  onError,
  className,
  style,
  unstyled = false,
}: MiosaApiKeyManagerProps): React.ReactElement {
  const [state, setState] = useState<State>({ status: "loading" });
  const [form, setForm] = useState<CreateForm>(DEFAULT_FORM);
  const [creating, setCreating] = useState(false);
  const [revealSecret, setRevealSecret] = useState<string | null>(null);
  const [revokingId, setRevokingId] = useState<string | null>(null);

  const load = useCallback(async () => {
    setState({ status: "loading" });
    try {
      const client = getClient(apiKey);
      const raw = await (
        client as unknown as {
          apiKeys: { list: () => Promise<unknown> };
        }
      ).apiKeys.list();
      const data = raw as { data?: ApiKey[] };
      setState({ status: "ready", keys: data.data ?? [] });
    } catch (err) {
      const error = err instanceof Error ? err : new Error(String(err));
      setState({ status: "error", error });
      onError?.(error);
    }
  }, [apiKey, onError]);

  useEffect(() => {
    void load();
  }, [load]);

  const toggleScope = useCallback((scope: string) => {
    setForm((f) => ({
      ...f,
      scopes: f.scopes.includes(scope)
        ? f.scopes.filter((s) => s !== scope)
        : [...f.scopes, scope],
    }));
  }, []);

  const handleCreate = useCallback(
    async (e: React.FormEvent) => {
      e.preventDefault();
      if (!form.name.trim() || creating) return;
      setCreating(true);
      try {
        const client = getClient(apiKey);
        const params: Record<string, unknown> = {
          name: form.name.trim(),
          scopes: form.scopes,
        };
        if (form.expires_at) params["expires_at"] = form.expires_at;
        if (form.isL2 && form.external_user_id) {
          params["external_user_id"] = form.external_user_id;
        }

        const endpoint = form.isL2 ? "createScoped" : "create";

        const raw = await (
          client as unknown as {
            apiKeys: Record<
              string,
              (p: Record<string, unknown>) => Promise<unknown>
            >;
          }
        ).apiKeys[endpoint]?.(params);

        const result = raw as { secret?: string };
        if (result.secret) {
          setRevealSecret(result.secret);
        }
        setForm(DEFAULT_FORM);
        await load();
      } catch (err) {
        const error = err instanceof Error ? err : new Error(String(err));
        onError?.(error);
      } finally {
        setCreating(false);
      }
    },
    [form, creating, apiKey, load, onError],
  );

  const handleRevoke = useCallback(
    async (keyId: string) => {
      if (!window.confirm("Revoke this API key? This cannot be undone."))
        return;
      setRevokingId(keyId);
      try {
        const client = getClient(apiKey);
        await (
          client as unknown as {
            apiKeys: { revoke: (p: { id: string }) => Promise<unknown> };
          }
        ).apiKeys.revoke({ id: keyId });
        await load();
      } catch (err) {
        const error = err instanceof Error ? err : new Error(String(err));
        onError?.(error);
      } finally {
        setRevokingId(null);
      }
    },
    [apiKey, load, onError],
  );

  const base = "miosa-akm";

  return (
    <div
      className={cn(
        !unstyled && base,
        !unstyled && `${base}--${theme}`,
        className,
      )}
      style={style}
      data-miosa-theme={theme}
    >
      {/* Reveal modal */}
      {revealSecret && (
        <div
          className={`${base}__modal-overlay`}
          role="dialog"
          aria-modal="true"
          aria-label="API key created"
        >
          <div className={`${base}__modal`}>
            <h3 className={`${base}__modal-title`}>API key created</h3>
            <p className={`${base}__modal-hint`}>
              Copy this secret now — it will not be shown again.
            </p>
            <code className={`${base}__secret`}>{revealSecret}</code>
            <button
              type="button"
              className={`${base}__copy-btn`}
              onClick={() => {
                void navigator.clipboard.writeText(revealSecret);
              }}
              aria-label="Copy secret to clipboard"
            >
              Copy
            </button>
            <button
              type="button"
              className={`${base}__modal-close`}
              onClick={() => setRevealSecret(null)}
              aria-label="Close"
            >
              Done
            </button>
          </div>
        </div>
      )}

      {/* Create form */}
      <form
        className={`${base}__create`}
        onSubmit={handleCreate}
        aria-label="Create API key"
      >
        <h3 className={`${base}__form-title`}>New API key</h3>
        <input
          type="text"
          className={`${base}__input`}
          placeholder="Key name"
          value={form.name}
          onChange={(e) => setForm((f) => ({ ...f, name: e.target.value }))}
          aria-label="Key name"
          required
        />

        <label className={`${base}__label`}>
          <input
            type="checkbox"
            checked={form.isL2}
            onChange={(e) => setForm((f) => ({ ...f, isL2: e.target.checked }))}
            aria-label="Scoped (L2) key"
          />{" "}
          Scoped (L2) — bound to an external user
        </label>

        {form.isL2 && (
          <input
            type="text"
            className={`${base}__input`}
            placeholder="external_user_id"
            value={form.external_user_id}
            onChange={(e) =>
              setForm((f) => ({ ...f, external_user_id: e.target.value }))
            }
            aria-label="External user ID"
          />
        )}

        <div className={`${base}__scopes`} role="group" aria-label="Scopes">
          {ALL_SCOPES.map((scope) => (
            <label key={scope} className={`${base}__scope-label`}>
              <input
                type="checkbox"
                checked={form.scopes.includes(scope)}
                onChange={() => toggleScope(scope)}
                aria-label={scope}
              />{" "}
              {scope}
            </label>
          ))}
        </div>

        <input
          type="datetime-local"
          className={`${base}__input`}
          value={form.expires_at}
          onChange={(e) =>
            setForm((f) => ({ ...f, expires_at: e.target.value }))
          }
          aria-label="Expiration date (optional)"
          title="Expiration date (optional)"
        />

        <button
          type="submit"
          className={`${base}__create-btn`}
          disabled={creating}
          aria-label="Create API key"
        >
          {creating ? "Creating…" : "Create key"}
        </button>
      </form>

      {/* Key list */}
      {state.status === "loading" && (
        <div className={`${base}__loading`} aria-busy="true">
          Loading…
        </div>
      )}
      {state.status === "error" && (
        <div className={`${base}__error`} role="alert">
          {state.error.message}
        </div>
      )}
      {state.status === "ready" && (
        <ul className={`${base}__list`} role="list" aria-label="API keys">
          {state.keys.map((k) => (
            <li key={k.id} className={`${base}__item`}>
              <div className={`${base}__item-info`}>
                <span className={`${base}__item-name`}>{k.name}</span>
                <code className={`${base}__item-last4`}>…{k.last4}</code>
                {k.external_user_id && (
                  <span className={`${base}__item-badge`}>L2</span>
                )}
              </div>
              <div className={`${base}__item-scopes`}>
                {k.scopes.map((s) => (
                  <span key={s} className={`${base}__scope-chip`}>
                    {s}
                  </span>
                ))}
              </div>
              <div className={`${base}__item-meta`}>
                <span>
                  Created {new Date(k.created_at).toLocaleDateString()}
                </span>
                {k.last_used_at && (
                  <span>
                    Last used {new Date(k.last_used_at).toLocaleDateString()}
                  </span>
                )}
                {k.expires_at && (
                  <span>
                    Expires {new Date(k.expires_at).toLocaleDateString()}
                  </span>
                )}
              </div>
              <button
                type="button"
                className={`${base}__revoke-btn`}
                onClick={() => void handleRevoke(k.id)}
                disabled={revokingId === k.id}
                aria-label={`Revoke ${k.name}`}
              >
                {revokingId === k.id ? "…" : "Revoke"}
              </button>
            </li>
          ))}
          {state.keys.length === 0 && (
            <li className={`${base}__empty`}>No API keys yet.</li>
          )}
        </ul>
      )}
    </div>
  );
}

// svelte/src/components/MiosaApiKeyManager.svelte
<script lang="ts">
  import { Miosa } from "@miosa/sdk";
  import { onMount } from "svelte";

  interface ApiKey { id: string; name: string; last4: string; scopes: string[]; created_at: string; last_used_at?: string; expires_at?: string; external_user_id?: string; }
  interface ApiKeySdk { apiKeys: { list: () => Promise<unknown>; create: (p: Record<string,unknown>) => Promise<unknown>; createScoped: (p: Record<string,unknown>) => Promise<unknown>; revoke: (p:{id:string}) => Promise<unknown> } }

  const ALL_SCOPES = ["sandboxes:read","sandboxes:write","computers:read","computers:write","storage:read","storage:write","databases:read","databases:write","usage:read","audit_log:read","tenant:admin"];

  interface Props {
    apiKey: string;
    theme?: "light" | "dark";
    unstyled?: boolean;
    onError?: (err: Error) => void;
    class?: string;
    style?: string;
  }

  let { apiKey, theme = "dark", unstyled = false, onError, class: className, style }: Props = $props();

  function asApi(key: string): ApiKeySdk { return new Miosa({ apiKey: key }) as unknown as ApiKeySdk; }

  let keys = $state<ApiKey[]>([]);
  let loading = $state(true);
  let error = $state<Error | null>(null);
  let creating = $state(false);
  let revealSecret = $state<string | null>(null);
  let revokingId = $state<string | null>(null);
  let formName = $state("");
  let formScopes = $state<string[]>([]);
  let formExpiresAt = $state("");
  let formIsL2 = $state(false);
  let formExternalUserId = $state("");

  async function load() {
    loading = true; error = null;
    try {
      const raw = await asApi(apiKey).apiKeys.list();
      keys = (raw as { data?: ApiKey[] }).data ?? [];
    } catch (e) { error = e instanceof Error ? e : new Error(String(e)); onError?.(error); }
    finally { loading = false; }
  }

  function toggleScope(scope: string) {
    formScopes = formScopes.includes(scope) ? formScopes.filter((s) => s !== scope) : [...formScopes, scope];
  }

  async function handleCreate(e: Event) {
    e.preventDefault();
    if (!formName.trim() || creating) return;
    creating = true;
    try {
      const params: Record<string,unknown> = { name: formName.trim(), scopes: formScopes };
      if (formExpiresAt) params["expires_at"] = formExpiresAt;
      if (formIsL2 && formExternalUserId) params["external_user_id"] = formExternalUserId;
      const fn = formIsL2 ? "createScoped" : "create";
      const raw = await asApi(apiKey).apiKeys[fn](params);
      const result = raw as { secret?: string };
      if (result.secret) revealSecret = result.secret;
      formName = ""; formScopes = []; formExpiresAt = ""; formIsL2 = false; formExternalUserId = "";
      await load();
    } catch (e) { onError?.(e instanceof Error ? e : new Error(String(e))); }
    finally { creating = false; }
  }

  async function handleRevoke(keyId: string) {
    if (!window.confirm("Revoke this API key? This cannot be undone.")) return;
    revokingId = keyId;
    try {
      await asApi(apiKey).apiKeys.revoke({ id: keyId });
      await load();
    } catch (e) { onError?.(e instanceof Error ? e : new Error(String(e))); }
    finally { revokingId = null; }
  }

  onMount(load);
</script>

<div class={[!unstyled && "miosa-akm", !unstyled && `miosa-akm--${theme}`, className].filter(Boolean).join(" ")} {style} data-miosa-theme={theme}>
  {#if revealSecret}
    <div class="miosa-akm__modal-overlay" role="dialog" aria-modal="true" aria-label="API key created">
      <div class="miosa-akm__modal">
        <h3 class="miosa-akm__modal-title">API key created</h3>
        <p class="miosa-akm__modal-hint">Copy this secret now — it will not be shown again.</p>
        <code class="miosa-akm__secret">{revealSecret}</code>
        <button type="button" class="miosa-akm__copy-btn" aria-label="Copy secret to clipboard" onclick={() => window.navigator.clipboard.writeText(revealSecret!)}>Copy</button>
        <button type="button" class="miosa-akm__modal-close" onclick={() => revealSecret = null}>Done</button>
      </div>
    </div>
  {/if}

  <form class="miosa-akm__create" aria-label="Create API key" onsubmit={handleCreate}>
    <h3 class="miosa-akm__form-title">New API key</h3>
    <input type="text" class="miosa-akm__input" placeholder="Key name" aria-label="Key name" bind:value={formName} required />
    <label class="miosa-akm__label"><input type="checkbox" aria-label="Scoped (L2) key" bind:checked={formIsL2} /> Scoped (L2) — bound to an external user</label>
    {#if formIsL2}
      <input type="text" class="miosa-akm__input" placeholder="external_user_id" aria-label="External user ID" bind:value={formExternalUserId} />
    {/if}
    <div class="miosa-akm__scopes" role="group" aria-label="Scopes">
      {#each ALL_SCOPES as scope}
        <label class="miosa-akm__scope-label">
          <input type="checkbox" checked={formScopes.includes(scope)} aria-label={scope} onchange={() => toggleScope(scope)} /> {scope}
        </label>
      {/each}
    </div>
    <input type="datetime-local" class="miosa-akm__input" aria-label="Expiration date (optional)" title="Expiration date (optional)" bind:value={formExpiresAt} />
    <button type="submit" class="miosa-akm__create-btn" disabled={creating} aria-label="Create API key">{creating ? "Creating…" : "Create key"}</button>
  </form>

  {#if loading}
    <div class="miosa-akm__loading" aria-busy="true">Loading…</div>
  {:else if error}
    <div class="miosa-akm__error" role="alert">{error.message}</div>
  {:else}
    <ul class="miosa-akm__list" role="list" aria-label="API keys">
      {#each keys as k (k.id)}
        <li class="miosa-akm__item">
          <div class="miosa-akm__item-info">
            <span class="miosa-akm__item-name">{k.name}</span>
            <code class="miosa-akm__item-last4">…{k.last4}</code>
            {#if k.external_user_id}<span class="miosa-akm__item-badge">L2</span>{/if}
          </div>
          <div class="miosa-akm__item-scopes">{#each k.scopes as s}<span class="miosa-akm__scope-chip">{s}</span>{/each}</div>
          <div class="miosa-akm__item-meta">
            <span>Created {new Date(k.created_at).toLocaleDateString()}</span>
            {#if k.last_used_at}<span>Last used {new Date(k.last_used_at).toLocaleDateString()}</span>{/if}
            {#if k.expires_at}<span>Expires {new Date(k.expires_at).toLocaleDateString()}</span>{/if}
          </div>
          <button type="button" class="miosa-akm__revoke-btn" disabled={revokingId === k.id} aria-label={`Revoke ${k.name}`} onclick={() => handleRevoke(k.id)}>
            {revokingId === k.id ? "…" : "Revoke"}
          </button>
        </li>
      {/each}
      {#if keys.length === 0}<li class="miosa-akm__empty">No API keys yet.</li>{/if}
    </ul>
  {/if}
</div>
