// react/src/components/MiosaPreview.tsx
import React, { useEffect, useRef, useState } from "react";
import { cn } from "../utils/cn.js";
import { getClient } from "../utils/client.js";
import type { MiosaAuth, MiosaBaseProps } from "../types.js";

export type MiosaPreviewProps = MiosaBaseProps &
  MiosaAuth & {
    sandboxId: string;
  };

type State =
  | { status: "idle" }
  | { status: "loading" }
  | { status: "ready"; url: string }
  | { status: "error"; error: Error };

export function MiosaPreview({
  sandboxId,
  previewToken,
  apiKey,
  theme = "dark",
  onError,
  className,
}: MiosaPreviewProps): React.ReactElement {
  const [state, setState] = useState<State>({ status: "idle" });
  const mountedRef = useRef(true);

  useEffect(() => {
    mountedRef.current = true;
    setState({ status: "loading" });

    let cancelled = false;

    async function resolve(): Promise<void> {
      try {
        if (previewToken) {
          // Consumer supplied a pre-minted token — build the iframe URL directly.
          // The platform embeds at: https://preview.miosa.ai/{sandboxId}?mt={token}
          const url = `https://preview.miosa.ai/${encodeURIComponent(sandboxId)}?mt=${encodeURIComponent(previewToken)}`;
          if (!cancelled) setState({ status: "ready", url });
          return;
        }

        if (!apiKey) return;
        const client = getClient(apiKey);
        // Fetch sandbox to get its preview URL / slug
        const sandbox = await client.sandboxes.get(sandboxId);
        // The API returns a preview_url field on the sandbox object
        const raw = sandbox as unknown as Record<string, unknown>;
        const previewUrl =
          typeof raw["preview_url"] === "string"
            ? raw["preview_url"]
            : `https://preview.miosa.ai/${encodeURIComponent(sandboxId)}`;
        if (!cancelled) setState({ status: "ready", url: previewUrl });
      } catch (err) {
        const error = err instanceof Error ? err : new Error(String(err));
        if (!cancelled) {
          setState({ status: "error", error });
          onError?.(error);
        }
      }
    }

    void resolve();

    return () => {
      cancelled = true;
      mountedRef.current = false;
    };
  }, [sandboxId, previewToken, apiKey, onError]);

  const base = "miosa-preview";

  if (state.status === "error") {
    return (
      <div
        className={cn(base, `${base}--error`, `${base}--${theme}`, className)}
        role="alert"
      >
        <span className={`${base}__error-text`}>
          Preview unavailable: {state.error.message}
        </span>
      </div>
    );
  }

  return (
    <div
      className={cn(base, `${base}--${theme}`, className)}
      data-miosa-theme={theme}
    >
      {state.status !== "ready" && (
        <div className={`${base}__skeleton`} aria-label="Loading preview" />
      )}
      {state.status === "ready" && (
        <iframe
          src={state.url}
          className={`${base}__frame`}
          title="Sandbox preview"
          sandbox="allow-scripts allow-same-origin allow-forms allow-popups"
          loading="lazy"
        />
      )}
    </div>
  );
}

// svelte/src/components/MiosaPreview.svelte
<script lang="ts">
  import { Miosa } from "@miosa/sdk";
  import { onDestroy, onMount } from "svelte";

  interface Props {
    sandboxId: string;
    previewToken?: string;
    apiKey?: string;
    theme?: "light" | "dark";
    class?: string;
  }

  let {
    sandboxId,
    previewToken,
    apiKey,
    theme = "light",
    class: className = "",
  }: Props = $props();

  let iframeUrl = $state<string | null>(null);
  let loading = $state(true);
  let error = $state<Error | null>(null);

  interface ComponentEvents {
    error: Error;
  }

  import { createEventDispatcher } from "svelte";
  const dispatch = createEventDispatcher<ComponentEvents>();

  async function resolveUrl() {
    loading = true;
    error = null;
    try {
      if (previewToken) {
        iframeUrl = `https://preview.miosa.app/${sandboxId}?token=${previewToken}`;
      } else if (apiKey) {
        const client = new Miosa({ apiKey });
        const sandbox = await client.sandboxes.get(sandboxId);
        const result = await (sandbox as any).previewToken(3600);
        iframeUrl = result.url;
      } else {
        throw new Error("Either previewToken or apiKey is required");
      }
    } catch (e) {
      const err = e instanceof Error ? e : new Error(String(e));
      error = err;
      dispatch("error", err);
    } finally {
      loading = false;
    }
  }

  onMount(resolveUrl);

  $effect(() => {
    void sandboxId;
    resolveUrl();
  });

  onDestroy(() => {
    iframeUrl = null;
  });
</script>

<div
  class={`miosa-preview miosa-preview--${theme} ${className}`}
  role="region"
  aria-label="Sandbox preview"
>
  {#if loading}
    <div class="miosa-preview__loading" aria-live="polite">Loading preview…</div>
  {:else if error}
    <div class="miosa-preview__error" role="alert">{error.message}</div>
  {:else if iframeUrl}
    <iframe
      src={iframeUrl}
      class="miosa-preview__frame"
      sandbox="allow-scripts allow-same-origin allow-forms"
      allow="clipboard-read; clipboard-write"
      title="Sandbox preview"
    ></iframe>
  {/if}
</div>

<style>
  .miosa-preview {
    position: relative;
    width: 100%;
    height: 100%;
    overflow: hidden;
    border-radius: 8px;
    background: #0d0d0d;
  }
  .miosa-preview--light {
    background: #f5f5f5;
  }
  .miosa-preview__frame {
    width: 100%;
    height: 100%;
    border: none;
  }
  .miosa-preview__loading,
  .miosa-preview__error {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 100%;
    height: 100%;
    font-family: system-ui, sans-serif;
    font-size: 14px;
    color: #888;
  }
  .miosa-preview__error {
    color: #e05c5c;
  }
</style>
